-- ─────────────────────────────────────────────────────────────────────────────
-- Migration 010 — Restauration de 30 joueurs de démonstration
-- ─────────────────────────────────────────────────────────────────────────────
-- Réinsère les 18 joueurs supprimés par la migration 009 (avec données enrichies)
-- et ajoute 12 nouveaux profils pour atteindre 30 joueurs démo au total.
-- 22 joueurs Israël + 8 joueurs France.
-- ON CONFLICT (id) DO UPDATE → idempotent, ré-exécutable sans risque.
-- ─────────────────────────────────────────────────────────────────────────────

SET session_replication_role = 'replica';

INSERT INTO public.profiles (
  id, name, age, level, city,
  dominant_hand, preferred_side, play_style, motivation, frequency,
  bio_fr, bio_en, bio_he,
  confidence_rate, matches_played, wins,
  is_demo, partner_prefs,
  created_at, updated_at
) VALUES

  -- ════════════════════════════════════════════════════════════════
  -- ISRAËL — 22 joueurs
  -- ════════════════════════════════════════════════════════════════

  ('b0000001-0000-0000-0000-000000000000', 'Adam Cohen', 28, 3.5, 'Tel Aviv',
   'right', 'forehand', 'defensive', 'improve', 3,
   'Padel passionné, toujours fair-play. Adore les échanges longs et tactiques.',
   'Passionate padel player, always fair. Loves long tactical rallies.',
   'שחקן פאדל נלהב, תמיד עם פיירפליי. אוהב חילופי כדורים ארוכים.',
   74, 28, 16, true,
   '{"hand":"right","side":"forehand","style":"defensive","motivation":"improve","levelMin":2.5,"levelMax":4.5}',
   NOW(), NOW()),

  ('b0000002-0000-0000-0000-000000000000', 'Daniel Katz', 32, 4.0, 'Jérusalem',
   'right', 'backhand', 'all-court', 'compete', 4,
   'Aime les matchs tactiques, très régulier en revers.',
   'Loves tactical matches, very consistent backhand.',
   'אוהב משחקים טקטיים, עם בקהנד עקבי מאוד.',
   80, 45, 27, true,
   '{"hand":"right","side":"backhand","style":"all-court","motivation":"compete","levelMin":3.5,"levelMax":5.0}',
   NOW(), NOW()),

  ('b0000003-0000-0000-0000-000000000000', 'David Peretz', 24, 2.5, 'Tel Aviv',
   'right', 'forehand', 'aggressive', 'fun', 2,
   'Débutant enthousiaste, apprend vite.',
   'Enthusiastic beginner, learning very fast.',
   'מתחיל נלהב, לומד מהר מאוד.',
   52, 8, 3, true,
   '{"hand":"any","side":"any","style":"any","motivation":"fun","levelMin":1.5,"levelMax":3.5}',
   NOW(), NOW()),

  ('b0000004-0000-0000-0000-000000000000', 'Eitan Shapiro', 35, 5.0, 'Haïfa',
   'left', 'backhand', 'all-court', 'compete', 5,
   'Compétiteur dans l''âme, gaucher redoutable au filet.',
   'Competitor at heart, formidable left-handed net player.',
   'מתחרה בנשמה, גוחניסט מסוכן ברשת.',
   92, 80, 55, true,
   '{"hand":"left","side":"backhand","style":"all-court","motivation":"compete","levelMin":4.0,"levelMax":6.0}',
   NOW(), NOW()),

  ('b0000005-0000-0000-0000-000000000000', 'Gabriel Amar', 26, 3.0, 'Tel Aviv',
   'right', 'forehand', 'defensive', 'fun', 2,
   'Régulier et fiable sur le court, excellent esprit d''équipe.',
   'Consistent and reliable on court, excellent team spirit.',
   'עקבי ואמין במגרש, רוח קבוצתית מצוינת.',
   64, 15, 7, true,
   '{"hand":"right","side":"any","style":"defensive","motivation":"fun","levelMin":2.0,"levelMax":4.0}',
   NOW(), NOW()),

  ('b0000006-0000-0000-0000-000000000000', 'Idan Goldman', 30, 4.5, 'Raanana',
   'right', 'backhand', 'all-court', 'improve', 4,
   'Joueur complet, aime construire le jeu en équipe.',
   'Complete player, loves building the game as a team.',
   'שחקן מלא, אוהב לבנות משחק עם שותף.',
   86, 60, 38, true,
   '{"hand":"right","side":"backhand","style":"all-court","motivation":"improve","levelMin":3.5,"levelMax":5.5}',
   NOW(), NOW()),

  ('b0000007-0000-0000-0000-000000000000', 'Jonathan Mizrahi', 27, 3.5, 'Netanya',
   'right', 'forehand', 'aggressive', 'fun', 3,
   'Toujours motivé, jeu explosif et offensif.',
   'Always motivated, explosive and offensive play.',
   'תמיד מוטיבציה, משחק נפיץ והתקפי.',
   70, 22, 12, true,
   '{"hand":"any","side":"forehand","style":"aggressive","motivation":"fun","levelMin":2.5,"levelMax":4.5}',
   NOW(), NOW()),

  ('b0000008-0000-0000-0000-000000000000', 'Leo Weiss', 22, 2.0, 'Tel Aviv',
   'right', 'forehand', 'defensive', 'fun', 1,
   'Nouveau sur les courts, apprend vite et avec le sourire.',
   'New to the courts, learning fast with a smile.',
   'חדש במגרש, לומד מהר ועם חיוך.',
   45, 4, 1, true,
   '{"hand":"any","side":"any","style":"any","motivation":"fun","levelMin":1.0,"levelMax":3.0}',
   NOW(), NOW()),

  ('b0000009-0000-0000-0000-000000000000', 'Liam Dadon', 29, 4.0, 'Herzliya',
   'left', 'backhand', 'aggressive', 'compete', 4,
   'Jeu dynamique et rapide, gaucher naturel redoutable.',
   'Dynamic and fast-paced game, formidable natural left-hander.',
   'משחק דינמי ומהיר, גוחניסט טבעי מסוכן.',
   78, 40, 24, true,
   '{"hand":"left","side":"backhand","style":"aggressive","motivation":"compete","levelMin":3.0,"levelMax":5.0}',
   NOW(), NOW()),

  ('b000000a-0000-0000-0000-000000000000', 'Michael Berger', 38, 5.5, 'Tel Aviv',
   'right', 'forehand', 'all-court', 'compete', 5,
   'Niveau avancé, vision du jeu exceptionnelle.',
   'Advanced level, exceptional game vision.',
   'רמה מתקדמת, ראיית משחק יוצאת דופן.',
   95, 120, 84, true,
   '{"hand":"any","side":"any","style":"all-court","motivation":"compete","levelMin":4.5,"levelMax":6.5}',
   NOW(), NOW()),

  ('b000000b-0000-0000-0000-000000000000', 'Nathan Biton', 25, 3.0, 'Ashdod',
   'right', 'backhand', 'aggressive', 'fun', 2,
   'Joueur polyvalent, aime les smash de derrière.',
   'Versatile player, loves smashing from the back.',
   'שחקן רב-גוני, אוהב סמאשים מהאחור.',
   60, 12, 5, true,
   '{"hand":"right","side":"any","style":"aggressive","motivation":"fun","levelMin":2.0,"levelMax":4.0}',
   NOW(), NOW()),

  ('b000000c-0000-0000-0000-000000000000', 'Noah Klein', 23, 2.5, 'Tel Aviv',
   'right', 'forehand', 'defensive', 'improve', 2,
   'Débutant très appliqué, progresse à chaque match.',
   'Very dedicated beginner, improving at every match.',
   'מתחיל מסור מאוד, משתפר בכל משחק.',
   50, 6, 2, true,
   '{"hand":"right","side":"forehand","style":"any","motivation":"improve","levelMin":1.5,"levelMax":3.5}',
   NOW(), NOW()),

  ('b000000d-0000-0000-0000-000000000000', 'Oliver Haddad', 31, 4.5, 'Ramat Gan',
   'left', 'backhand', 'all-court', 'compete', 4,
   'Finesse et précision, gaucher de haut niveau.',
   'Finesse and precision, high-level left-hander.',
   'עדינות ודיוק, גוחניסט ברמה גבוהה.',
   88, 65, 42, true,
   '{"hand":"left","side":"backhand","style":"all-court","motivation":"compete","levelMin":3.5,"levelMax":5.5}',
   NOW(), NOW()),

  ('b000000e-0000-0000-0000-000000000000', 'Oscar Rosen', 28, 3.5, 'Tel Aviv',
   'right', 'forehand', 'defensive', 'improve', 3,
   'Régulier et constant, adore améliorer sa technique.',
   'Regular and consistent, loves improving his technique.',
   'סדיר ועקבי, אוהב לשפר את הטכניקה שלו.',
   72, 30, 17, true,
   '{"hand":"right","side":"forehand","style":"defensive","motivation":"improve","levelMin":2.5,"levelMax":4.5}',
   NOW(), NOW()),

  ('b000000f-0000-0000-0000-000000000000', 'Paul Azoulay', 40, 6.0, 'Jérusalem',
   'right', 'backhand', 'all-court', 'compete', 5,
   'Élite du padel local, cherche des adversaires à sa hauteur.',
   'Local padel elite, looking for opponents at his level.',
   'אליטת הפאדל המקומית, מחפש יריבים ברמתו.',
   98, 200, 148, true,
   '{"hand":"any","side":"backhand","style":"all-court","motivation":"compete","levelMin":5.0,"levelMax":7.0}',
   NOW(), NOW()),

  ('b0000010-0000-0000-0000-000000000000', 'Rafael Meyer', 33, 4.0, 'Haïfa',
   'right', 'forehand', 'defensive', 'improve', 3,
   'Joueur solide au fond du court, défense de béton.',
   'Solid player at the back of the court, iron defence.',
   'שחקן יציב בקו האחורי, הגנה כמו פלדה.',
   76, 38, 21, true,
   '{"hand":"right","side":"forehand","style":"defensive","motivation":"improve","levelMin":3.0,"levelMax":5.0}',
   NOW(), NOW()),

  ('b0000011-0000-0000-0000-000000000000', 'Sam Abutbul', 26, 3.0, 'Petah Tikva',
   'right', 'forehand', 'aggressive', 'fun', 2,
   'Sociable et bon état d''esprit, toujours partant pour jouer.',
   'Sociable with a great attitude, always up for a game.',
   'חברותי ועם גישה מצוינת, תמיד מוכן לשחק.',
   62, 10, 4, true,
   '{"hand":"any","side":"any","style":"aggressive","motivation":"fun","levelMin":2.0,"levelMax":4.0}',
   NOW(), NOW()),

  ('b0000012-0000-0000-0000-000000000000', 'Tom Feldman', 34, 4.5, 'Tel Aviv',
   'left', 'backhand', 'aggressive', 'compete', 5,
   'Technique soignée, jeu puissant et varié.',
   'Polished technique, powerful and varied game.',
   'טכניקה מוקפדת, משחק חזק ומגוון.',
   90, 70, 48, true,
   '{"hand":"left","side":"backhand","style":"aggressive","motivation":"compete","levelMin":4.0,"levelMax":6.0}',
   NOW(), NOW()),

  -- ── Nouveaux joueurs Israël ────────────────────────────────────────────

  ('b0000013-0000-0000-0000-000000000000', 'Yael Ben-David', 27, 3.5, 'Herzliya',
   'right', 'forehand', 'all-court', 'improve', 3,
   'Jeu complet et équilibré, toujours ouverte aux conseils.',
   'Complete and balanced game, always open to advice.',
   'משחק מלא ומאוזן, תמיד פתוחה לעצות.',
   68, 18, 10, true,
   '{"hand":"right","side":"forehand","style":"any","motivation":"improve","levelMin":2.5,"levelMax":4.5}',
   NOW(), NOW()),

  ('b0000014-0000-0000-0000-000000000000', 'Roi Golan', 30, 4.0, 'Tel Aviv',
   'left', 'forehand', 'aggressive', 'compete', 4,
   'Gaucher combatif, smash redoutable depuis tous les angles.',
   'Combative left-hander, formidable smash from all angles.',
   'גוחניסט לוחמני, סמאש מסוכן מכל הזוויות.',
   82, 50, 31, true,
   '{"hand":"left","side":"any","style":"aggressive","motivation":"compete","levelMin":3.0,"levelMax":5.0}',
   NOW(), NOW()),

  ('b0000015-0000-0000-0000-000000000000', 'Maya Ofer', 25, 3.0, 'Raanana',
   'right', 'backhand', 'defensive', 'fun', 2,
   'Joueuse régulière, bonne ambiance garantie sur le court.',
   'Consistent player, great atmosphere guaranteed on court.',
   'שחקנית עקבית, אווירה טובה מובטחת במגרש.',
   58, 14, 6, true,
   '{"hand":"right","side":"any","style":"defensive","motivation":"fun","levelMin":2.0,"levelMax":4.0}',
   NOW(), NOW()),

  ('b0000016-0000-0000-0000-000000000000', 'Noa Friedman', 28, 4.5, 'Tel Aviv',
   'right', 'forehand', 'all-court', 'improve', 4,
   'Joueuse polyvalente et sérieuse, cherche des partenaires motivés.',
   'Versatile and serious player, looking for motivated partners.',
   'שחקנית רב-גונית ורצינית, מחפשת שותפים מוטיבציוניים.',
   85, 55, 35, true,
   '{"hand":"right","side":"forehand","style":"all-court","motivation":"improve","levelMin":3.5,"levelMax":5.5}',
   NOW(), NOW()),

  -- ════════════════════════════════════════════════════════════════
  -- FRANCE — 8 joueurs
  -- ════════════════════════════════════════════════════════════════

  ('b0000017-0000-0000-0000-000000000000', 'Sophie Lévy', 28, 3.5, 'Paris',
   'right', 'forehand', 'all-court', 'improve', 3,
   'Joueuse parisienne passionnée, progression rapide.',
   'Passionate Parisian player, improving rapidly.',
   'שחקנית פריזאית נלהבת, מתקדמת במהירות.',
   70, 20, 11, true,
   '{"hand":"right","side":"forehand","style":"any","motivation":"improve","levelMin":2.5,"levelMax":4.5}',
   NOW(), NOW()),

  ('b0000018-0000-0000-0000-000000000000', 'Maxime Durand', 32, 4.0, 'Lyon',
   'right', 'backhand', 'aggressive', 'compete', 4,
   'Joueur lyonnais dynamique, aime les matchs intenses.',
   'Dynamic Lyon player, loves intense matches.',
   'שחקן ליונאי דינמי, אוהב משחקים אינטנסיביים.',
   78, 42, 25, true,
   '{"hand":"right","side":"backhand","style":"aggressive","motivation":"compete","levelMin":3.0,"levelMax":5.0}',
   NOW(), NOW()),

  ('b0000019-0000-0000-0000-000000000000', 'Camille Martin', 25, 3.0, 'Paris',
   'left', 'forehand', 'defensive', 'fun', 2,
   'Gauchère souriante, joue pour le plaisir avant tout.',
   'Smiling left-hander, plays for the love of the game.',
   'גוחניסטית עם חיוך, משחקת בשביל האהבה למשחק.',
   58, 10, 4, true,
   '{"hand":"any","side":"any","style":"defensive","motivation":"fun","levelMin":1.5,"levelMax":4.0}',
   NOW(), NOW()),

  ('b000001a-0000-0000-0000-000000000000', 'Lucas Bernard', 35, 5.0, 'Marseille',
   'right', 'backhand', 'all-court', 'compete', 5,
   'Joueur marseillais de haut niveau, cherche le défi permanent.',
   'High-level Marseille player, always seeking a challenge.',
   'שחקן מרסיה ברמה גבוהה, תמיד מחפש אתגרים.',
   92, 90, 62, true,
   '{"hand":"right","side":"backhand","style":"all-court","motivation":"compete","levelMin":4.0,"levelMax":6.0}',
   NOW(), NOW()),

  ('b000001b-0000-0000-0000-000000000000', 'Emilie Rossi', 29, 3.5, 'Nice',
   'right', 'forehand', 'defensive', 'improve', 3,
   'Joueuse niçoise, finesse et régularité.',
   'Nice-based player, finesse and consistency.',
   'שחקנית מניס, עדינות ועקביות.',
   68, 22, 12, true,
   '{"hand":"right","side":"forehand","style":"defensive","motivation":"improve","levelMin":2.5,"levelMax":4.5}',
   NOW(), NOW()),

  ('b000001c-0000-0000-0000-000000000000', 'Antoine Moreau', 31, 4.5, 'Bordeaux',
   'left', 'backhand', 'aggressive', 'compete', 4,
   'Gaucher bordelais explosif, smash dévastateur.',
   'Explosive left-handed player from Bordeaux, devastating smash.',
   'גוחניסט נפיץ מבורדו, סמאש הרסני.',
   87, 62, 40, true,
   '{"hand":"left","side":"backhand","style":"aggressive","motivation":"compete","levelMin":3.5,"levelMax":5.5}',
   NOW(), NOW()),

  ('b000001d-0000-0000-0000-000000000000', 'Juliette Petit', 24, 2.5, 'Toulouse',
   'right', 'forehand', 'all-court', 'fun', 2,
   'Débutante toulousaine enthousiaste, apprentissage joyeux.',
   'Enthusiastic beginner from Toulouse, joyful learning.',
   'מתחילה נלהבת מטולוז, למידה שמחה.',
   48, 6, 2, true,
   '{"hand":"any","side":"any","style":"any","motivation":"fun","levelMin":1.5,"levelMax":3.5}',
   NOW(), NOW()),

  ('b000001e-0000-0000-0000-000000000000', 'Théo Garnier', 30, 4.0, 'Lille',
   'right', 'backhand', 'defensive', 'improve', 3,
   'Joueur lillois solide et constant, défense très organisée.',
   'Solid and consistent Lille player, very organised defence.',
   'שחקן מליל יציב ועקבי, הגנה מאוד מאורגנת.',
   74, 35, 19, true,
   '{"hand":"right","side":"backhand","style":"defensive","motivation":"improve","levelMin":3.0,"levelMax":5.0}',
   NOW(), NOW())

ON CONFLICT (id) DO UPDATE SET
  name           = EXCLUDED.name,
  age            = EXCLUDED.age,
  level          = EXCLUDED.level,
  city           = EXCLUDED.city,
  dominant_hand  = EXCLUDED.dominant_hand,
  preferred_side = EXCLUDED.preferred_side,
  play_style     = EXCLUDED.play_style,
  motivation     = EXCLUDED.motivation,
  frequency      = EXCLUDED.frequency,
  bio_fr         = EXCLUDED.bio_fr,
  bio_en         = EXCLUDED.bio_en,
  bio_he         = EXCLUDED.bio_he,
  confidence_rate = EXCLUDED.confidence_rate,
  matches_played = EXCLUDED.matches_played,
  wins           = EXCLUDED.wins,
  partner_prefs  = EXCLUDED.partner_prefs,
  is_demo        = true,
  updated_at     = NOW();

SET session_replication_role = DEFAULT;
